base_url = "https://softoy.github.io/"
title = "Softoy的笔记本"
description = "写点杂七杂八的东西, 东西比较零碎"
compile_sass = false

build_search_index = false
generate_feeds = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Put all your custom variables here

[extra.profile]
name = "Softoy's Notes"
bio = "写点杂七杂八的东西"
avatar_url = "icons/github.svg"
avatar_invert = true

[[extra.profile.social]]
name = "rss"
url = "$BASE_URL/atom.xml"

[extra.footer]
since = 2025
license = "CC BY-SA 4.0"
license_url = "https://creativecommons.org/licenses/by-sa/4.0/deed"