name: Deploy Zola to GH Pages
on: push
jobs:
  zola-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: knzai/zola-cli@install
    - uses: knzai/zola-cli@build
    - uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: public
      
