name: Deploy Zola to GH Pages
on: push
jobs:
  zola-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: knzai/zola-build@main
      with:
        check: false
      
